### ISSUE TITLE
Discrepancy between paper and code 

### ISSUE THREAD

**Issue by LukasMosser** [ZezhouCheng/GP-DIP#1]
Dear authors,

Thank you for sharing your implementation to your paper. It's a very valuable resource for learning. 

Could you please explain the discrepancy between the paper and the notebook '''Image_Inpainting.ipynb'''. In the paper you state you use SGD and SGLD, but in the code you use Adam and Adam+noise. The latter is actually more closely related to stochastic gradient Hamiltonian or Riemannian monte carlo methods. 

Regardless, could you explain the discrepancy and maybe update on which is correct, the paper or the code?

Many thanks

**Comment by LukasMosser** [comment]
Have you been able to look into this?

**Comment by ZezhouCheng** [comment]
Hi Lukas, thanks for your interest in our work! It is true that we use Adam instead of vanilla SGD, which works much better in practice with deep networks. Because of this our method is indeed more closely related to Riemannian SGLD or preconditioned SGLD (Li et al., AAAI 16) since ADAM performs a diagonal approximation of the preconditioning matrix.

**Comment by LukasMosser** [comment]
Thanks for clarifying.
